output_dir: '../MDPS-vis-master/output'

axis_to_csv_dic:
  'F': ['x.csv', 'z.csv']
  'S': ['y.csv', 'z.csv']
  'T': ['x.csv', 'y.csv']

conversion_factors:
  {
    '1001': {'F': 0.074627, 'S': 0.111111},
    '1008': {'F': 0.075757576, 'S': 0.177777778},
    '1011': {'F': 0.075757576},
    '1012': {'F': 0.046296296},
    '1024': {'F': 0.044642857, 'S': 0.075471698},
    '1029': {'F': 0.044642857, 'S': 0.075471698},
    '1102': {'F': {'A': 0.0485, 'B': 0.0485}, 'S': {'A': 0.069565217, 'B': 0.066666667}},
    '1103': {'F': {'A': 0.0485, 'B': 0.0485}},
    '1104': {'F': {'A': 0.05, 'B': 0.05}, 'S': {'A': 0.067796610, 'B': 0.065040650}},
    '1105': {'F': {'H': 0.0479, 'IR': 0.05, 'OR': 0.05, 'B': 0.05}}
    }

sample_size: 2048
overlap: 1024

epochs: 100
batch_size: 128