seed: 42

output_dir: '../MDPS-vis-master/output'
model_dir: './saved'
log_txt: './log/experiment_results.csv'
feature_figs_dir: './feature_distribution_figs'

axis_to_csv_dic:
  'F': ['x.csv', 'z.csv']
  'S': ['y.csv', 'z.csv']
  'T': ['x.csv', 'y.csv']

label_dic:
    'B' : 0
    'H' : 1
    'IR': 2
    'OR': 3

class2label_dic:
    0 : 'B'
    1 : 'H'
    2 : 'IR'
    3 : 'OR'

conversion_factors:
  {
    '1001': {'F': 0.074627, 'S': 0.111111},
    '1008': {'F': 0.075757576, 'S': 0.177777778},
    '1011': {'F': 0.075757576},
    '1012': {'F': 0.046296296},
    '1024': {'F': 0.044642857, 'S': 0.075471698},
    '1029': {'F': 0.044642857, 'S': 0.075471698},
    '1102': {'F': {'A': 0.0485, 'B': 0.0485}, 'S': {'A': 0.069565217, 'B': 0.066666667}},
    '1103': {'F': {'A': 0.0485, 'B': 0.0485}},
    '1104': {'F': {'A': 0.05, 'B': 0.05}, 'S': {'A': 0.067796610, 'B': 0.065040650}},
    '1105': {'F': {'H': 0.0479, 'IR': 0.05, 'OR': 0.05, 'B': 0.05}},
    '1217': {'F': {'H': 0.0625, 'IR': 0.0632911392405063, 'OR': 0.0632911392405063, 'B': 0.0632911392405063}}
    }

# 데이터를 읽을 샘플 크기와 오버랩 정도
sample_size: 2048
overlap: 1024

# 훈련 관련 파라미터
epochs: 50
batch_size: 64
lr: 0.001