# 실험 환경 관련 파라미터
# 영상 위치 번호
video_root: './videos/'
date: '0828'
bearing_type: '30204'
fault_type: 'H'
rpm: 1200
fps: 120
axis: 'X'



# 변위 추출 파라미터
skip: 0
fo: 14
flb: 0.01
fub: 1.0
a: 0

lb: [90, 50, 60]
ub: [140, 255, 255]