video_root: './videos'
output_root: './output'

rpm: 1200
fps: 120

fault_type_list:
  - 'H'
  - 'IR'
  - 'OR'
  - 'B'

axis_list:
  - 'F'
  - 'S'
  - 'T'

axis_to_csv_dic:
  'F': ['x.csv', 'z.csv']
  'S': ['y.csv', 'z.csv']
  'T': ['x.csv', 'y.csv']

axis_to_marker_dic:
  'F' : ['A', 'B']
  'S' : ['A', 'B']
  'T' : ['A', 'B', 'C', 'D', 'E']


# 변위 추출 파라미터
skip: 0
fo: 14
flb: 0.01
fub: 1.0
a: 0
